### ISSUE TITLE
Support the migration to Rails 5

### ISSUE THREAD

**Issue by Xhamps** [getninjas/data_migrater#3]
I installed the `data_migrater`, but when running the `rake db:migration` throw this exception.

```shell
StandardError: An error has occurred, all later migrations canceled:

Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateDataMigrations < ActiveRecord::Migration[4.2]
```

To fix this i need specify the Rails release in the migration.
Do you support the Rails 5 in the future?

**Comment by wbotelhos** [comment]
Hi @Xhamps ,

What version are you using?
Could you try to drop the `[4.2]` specification? I did no find it in the code.

**Comment by Xhamps** [comment]
I'm using the version `5.1`. I don't know why the error message show `4.2`

When created a new `data_migrater` don't specify the version, in others migration generated by rails specify the version `[5.1]`, to fix this I added this string after inheritance and it running okay

**Comment by wbotelhos** [comment]
Nice @Xhamps ,

So far, I created a [brach with Rails 5 support](https://github.com/getninjas/data_migrater/tree/rails5)  for you.
You can use it adding that to your Gemfile:

```ruby
gem 'data_migrater', github: 'getninjas/data_migrater', branch: 'rails5'
```

If you have some problem, let me know. (:

**Comment by Xhamps** [comment]
Thanks @wbotelhos..
